 '''
name: Python Matrix Operations
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: python file.py
 

  Secret-access:
   needs: build
   runs-on: ubuntu-latest
 
   if: ${{always()}}
 
   steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: use a secret variable
      env: 
       my-secret: ${{secrets.my_secret_token}}
      run: |
       echo "my secret is $my-secret"
'''
name: Python Program
 
on:
  workflow_dispatch
 
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-latest
 
    # strategy:
    #   matrix:
    #     python-versions: [3.12, 3.9, 3.8]
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-versions }}
 
      - name: Run Python Program
        run: |
          python index.py
 